### ISSUE TITLE
RuntimeError: Attempting to deserialize object on CUDA device 6 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

### ISSUE THREAD

**Issue by JacekKedzierski** [MatthewMasters/EDM-Dock#1]
input:
python scripts/dock.py --run_path runs/paper_baseline --dataset_path examples

output:
Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing
Using weights from... runs/paper_baseline/weights.ckpt
set seed for random, numpy and torch
Traceback (most recent call last):
  File "/home/jacek/EDMDockTutorial/EDM-Dock/scripts/dock.py", line 119, in <module>
    model.load_state_dict(torch.load(weight_path)['state_dict'])
  File "/home/jacek/Install/miniconda3/envs/edm-dock/lib/python3.9/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/jacek/Install/miniconda3/envs/edm-dock/lib/python3.9/site-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/home/jacek/Install/miniconda3/envs/edm-dock/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/jacek/Install/miniconda3/envs/edm-dock/lib/python3.9/pickle.py", line 1253, in load_binpersid
    self.append(self.persistent_load(pid))
  File "/home/jacek/Install/miniconda3/envs/edm-dock/lib/python3.9/site-packages/torch/serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/jacek/Install/miniconda3/envs/edm-dock/lib/python3.9/site-packages/torch/serialization.py", line 1001, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/jacek/Install/miniconda3/envs/edm-dock/lib/python3.9/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/jacek/Install/miniconda3/envs/edm-dock/lib/python3.9/site-packages/torch/serialization.py", line 152, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/jacek/Install/miniconda3/envs/edm-dock/lib/python3.9/site-packages/torch/serialization.py", line 143, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 6 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

**Comment by MADSNORREGAARD** [comment]
Have exact same experience

**Comment by jiaxin-ustc** [comment]
this page give the solution, it works for me, https://www.jianshu.com/p/ec91b3b59f66

**Comment by MatthewMasters** [comment]
Sorry for the late response here. This issue arises since the original weights were trained on CUDA device 6, so you will encounter issues if you try to load to this device and don't have a cuda device 6. This should be resolvable by simply adding `map_location=torch.device('cpu')` like:
```
model.load_state_dict(torch.load(weight_path, map_location=torch.device('cpu'))['state_dict'])
```

I was not able to replicate this issue on my own system. But should anyone still encounter issues, feel free to reopen the issue.
