### ISSUE TITLE
no module named openforcefield

### ISSUE THREAD

**Issue by lffzhang** [MatthewMasters/EDM-Dock#5]
as i use the command 
python scripts/dock.py 
there is a error,and i can't find the module 'openforcefield' , how can i solve this problem?

Traceback (most recent call last):
  File "/home/zlf/Downloads/EDM-Dock/scripts/dock.py", line 12, in <module>
    from edmdock.utils.dock import Minimizer
  File "/home/zlf/anaconda3/envs/edmdock/lib/python3.9/site-packages/EDM_Dock-1.0-py3.9.egg/edmdock/utils/dock.py", line 8, in <module>
    from openforcefield.topology import Molecule
ModuleNotFoundError: No module named 'openforcefield'

**Comment by patjiang** [comment]
Hello, have you tried installing openforcefield? Here are the associated documentations: https://docs.openforcefield.org/projects/toolkit/en/latest/installation.html
