### ISSUE TITLE
ModuleNotFoundError: No module named 'openforcefield'

### ISSUE THREAD

**Issue by chiragpatel269** [MatthewMasters/EDM-Dock#7]
Input:
python3 scripts/dock.py --run_path runs/paper_baseline --dataset_path ./examples

Output:
Traceback (most recent call last):
  File "/Users/chiragpatel/Desktop/EDM-Dock/scripts/dock.py", line 12, in <module>
    from edmdock.utils.dock import Minimizer
  File "/Users/chiragpatel/anaconda3/envs/edm-dock/lib/python3.10/site-packages/EDM_Dock-1.0-py3.10.egg/edmdock/utils/dock.py", line 8, in <module>
    from openforcefield.topology import Molecule
ModuleNotFoundError: No module named 'openforcefield'

**Comment by patjiang** [comment]
I was able to resole this issue by replacing openforcefield with "openff.toolkit.topology"
